version: "2.1"
volumes:
  domotz-data:
services:
  domotz:
    image: avassdal/domotz-arm64
    network_mode: "host"
    container_name: domotz
    ports:
    - "3000:3000"
    volumes:
     - domotz-data:/opt/domotz/etc/
    cap_add:
     - ALL
    restart: unless-stopped
    privileged: true


  openwrt:
    image: avassdal/openwrt
    network_mode: "host"

include:
  ./netbox/docker-compose.yml
